version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

image: Visual Studio 2019

configuration: Release

before_build:
- cmd: nuget restore

build:
  verbosity: minimal
  
test:
  categories:
    except:
    - RequiresExcel

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: I1v6kjAxV9OU3tuJ7U6RJjji3Rnrcf7jzQpw89YKEiqEDyD3xieqNHV7VRCfjSCC
  artifact: /.*\.nupkg/
