version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  categories:
    except:
    - RequiresExcel
after_test:
  - ps: .\nuget\pack.ps1
