version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

image: Visual Studio 2019

configuration: Release

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

build_script:
 - choco install "sonarscanner-msbuild-net46" -y
 - SonarScanner.MSBuild.exe begin /k:"SimpleExcelReport" /d:"sonar.host.url=https://sonarcloud.io" /o:"dylantowler" /d:"sonar.login="26dac627a51daf1beaff1428f8abbd4ddf68aba4"
 - msbuild /verbosity:minimal "SimpleExcelReport.sln"
 - SonarScanner.MSBuild.exe end /d:"sonar.login=26dac627a51daf1beaff1428f8abbd4ddf68aba4"

test:
  categories:
    except:
    - RequiresExcel

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: I1v6kjAxV9OU3tuJ7U6RJjji3Rnrcf7jzQpw89YKEiqEDyD3xieqNHV7VRCfjSCC
  artifact: /.*\.nupkg/
